  version: "3.0"
  services:
    sporting-frontend:
      build:
          context: ./
          dockerfile: Dockerfile
      container_name: centre-front
      ports:
        - "3000:3000"
      volumes:
        - ./
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true  # Enables hot-reloading in Docker
        - WATCHPACK_POLLING=true    # Enable file watching
        - NODE_ENV=development
          # Add any other environment variables your React app needs
        - REACT_APP_API_URL=http://localhost:8880
      networks:
        - app-network
  
  networks:
    app-network:
      driver: bridge
      